const String SplashRoute= '/splash';
const String HomeRoute= '/home';
const String SearchRoute= '/search';
const String FavoriteRoute= '/favorite';
const String ProfileRoute= '/profile';
const String MyOrderRoute= '/myOrder';
const String CategoryRoomsRoute='/category';
const String ProductDetailsRoute='/details';
const String TransportRoute='/transport';
